package com.jgeppert.struts2.jquery.grid.showcase.model;

// Generated 12.01.2010 14:13:15 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMERS", schema = "CLASSICMODELS")
public class Customers implements java.io.Serializable {

  private Integer customernumber;
  private String  customername;
  private String  contactlastname;
  private String  contactfirstname;
  private String  phone;
  private String  addressline1;
  private String  addressline2;
  private String  city;
  private String  state;
  private String  postalcode;
  private String  country;
  private Integer salesrepemployeenumber;
  private Double  creditlimit;

  public Customers() {
  }

  public Customers(Integer customernumber) {
    this.customernumber = customernumber;
  }

  public Customers(
      Integer customernumber,
      String customername,
      String contactlastname,
      String contactfirstname,
      String phone,
      String addressline1,
      String addressline2,
      String city,
      String state,
      String postalcode,
      String country,
      Integer salesrepemployeenumber,
      Double creditlimit) {
    this.customernumber = customernumber;
    this.customername = customername;
    this.contactlastname = contactlastname;
    this.contactfirstname = contactfirstname;
    this.phone = phone;
    this.addressline1 = addressline1;
    this.addressline2 = addressline2;
    this.city = city;
    this.state = state;
    this.postalcode = postalcode;
    this.country = country;
    this.salesrepemployeenumber = salesrepemployeenumber;
    this.creditlimit = creditlimit;
  }

  @Id
  @Column(name = "CUSTOMERNUMBER", unique = true)
  public Integer getCustomernumber()
  {
    return this.customernumber;
  }

  public void setCustomernumber(Integer customernumber)
  {
    this.customernumber = customernumber;
  }

  @Column(name = "CUSTOMERNAME", length = 50)
  public String getCustomername()
  {
    return this.customername;
  }

  public void setCustomername(String customername)
  {
    this.customername = customername;
  }

  @Column(name = "CONTACTLASTNAME", length = 50)
  public String getContactlastname()
  {
    return this.contactlastname;
  }

  public void setContactlastname(String contactlastname)
  {
    this.contactlastname = contactlastname;
  }

  @Column(name = "CONTACTFIRSTNAME", length = 50)
  public String getContactfirstname()
  {
    return this.contactfirstname;
  }

  public void setContactfirstname(String contactfirstname)
  {
    this.contactfirstname = contactfirstname;
  }

  @Column(name = "PHONE", length = 50)
  public String getPhone()
  {
    return this.phone;
  }

  public void setPhone(String phone)
  {
    this.phone = phone;
  }

  @Column(name = "ADDRESSLINE1", length = 50)
  public String getAddressline1()
  {
    return this.addressline1;
  }

  public void setAddressline1(String addressline1)
  {
    this.addressline1 = addressline1;
  }

  @Column(name = "ADDRESSLINE2", length = 50)
  public String getAddressline2()
  {
    return this.addressline2;
  }

  public void setAddressline2(String addressline2)
  {
    this.addressline2 = addressline2;
  }

  @Column(name = "CITY", length = 50)
  public String getCity()
  {
    return this.city;
  }

  public void setCity(String city)
  {
    this.city = city;
  }

  @Column(name = "STATE", length = 50)
  public String getState()
  {
    return this.state;
  }

  public void setState(String state)
  {
    this.state = state;
  }

  @Column(name = "POSTALCODE", length = 15)
  public String getPostalcode()
  {
    return this.postalcode;
  }

  public void setPostalcode(String postalcode)
  {
    this.postalcode = postalcode;
  }

  @Column(name = "COUNTRY", length = 50)
  public String getCountry()
  {
    return this.country;
  }

  public void setCountry(String country)
  {
    this.country = country;
  }

  @Column(name = "SALESREPEMPLOYEENUMBER")
  public Integer getSalesrepemployeenumber()
  {
    return this.salesrepemployeenumber;
  }

  public void setSalesrepemployeenumber(Integer salesrepemployeenumber)
  {
    this.salesrepemployeenumber = salesrepemployeenumber;
  }

  @Column(name = "CREDITLIMIT", precision = 52, scale = 0)
  public Double getCreditlimit()
  {
    return this.creditlimit;
  }

  public void setCreditlimit(Double creditlimit)
  {
    this.creditlimit = creditlimit;
  }

}
