package com.jgeppert.struts2.jquery.grid.showcase.model;

// Generated 12.01.2010 14:13:15 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEES", schema = "CLASSICMODELS")
public class Employees implements java.io.Serializable {

  private Integer employeenumber;
  private String  lastname;
  private String  firstname;
  private String  extension;
  private String  email;
  private String  officecode;
  private Integer reportsto;
  private String  jobtitle;

  public Employees() {
  }

  public Employees(Integer employeenumber) {
    this.employeenumber = employeenumber;
  }

  public Employees(Integer employeenumber, String lastname, String firstname, String extension, String email, String officecode, Integer reportsto, String jobtitle) {
    this.employeenumber = employeenumber;
    this.lastname = lastname;
    this.firstname = firstname;
    this.extension = extension;
    this.email = email;
    this.officecode = officecode;
    this.reportsto = reportsto;
    this.jobtitle = jobtitle;
  }

  @Id
  @Column(name = "EMPLOYEENUMBER", unique = true)
  public Integer getEmployeenumber()
  {
    return this.employeenumber;
  }

  public void setEmployeenumber(Integer employeenumber)
  {
    this.employeenumber = employeenumber;
  }

  @Column(name = "LASTNAME", length = 50)
  public String getLastname()
  {
    return this.lastname;
  }

  public void setLastname(String lastname)
  {
    this.lastname = lastname;
  }

  @Column(name = "FIRSTNAME", length = 50)
  public String getFirstname()
  {
    return this.firstname;
  }

  public void setFirstname(String firstname)
  {
    this.firstname = firstname;
  }

  @Column(name = "EXTENSION", length = 10)
  public String getExtension()
  {
    return this.extension;
  }

  public void setExtension(String extension)
  {
    this.extension = extension;
  }

  @Column(name = "EMAIL", length = 100)
  public String getEmail()
  {
    return this.email;
  }

  public void setEmail(String email)
  {
    this.email = email;
  }

  @Column(name = "OFFICECODE", length = 10)
  public String getOfficecode()
  {
    return this.officecode;
  }

  public void setOfficecode(String officecode)
  {
    this.officecode = officecode;
  }

  @Column(name = "REPORTSTO")
  public Integer getReportsto()
  {
    return this.reportsto;
  }

  public void setReportsto(Integer reportsto)
  {
    this.reportsto = reportsto;
  }

  @Column(name = "JOBTITLE", length = 50)
  public String getJobtitle()
  {
    return this.jobtitle;
  }

  public void setJobtitle(String jobtitle)
  {
    this.jobtitle = jobtitle;
  }

}
