package com.jgeppert.struts2.jquery.grid.showcase.model;

// Generated 12.01.2010 14:13:15 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "ORDERS", schema = "CLASSICMODELS", uniqueConstraints = @UniqueConstraint(columnNames = "ORDERNUMBER"))
public class Orders implements java.io.Serializable {

  private Integer ordernumber;
  private Date    orderdate;
  private Date    requireddate;
  private Date    shippeddate;
  private String  status;
  private String  comments;
  private Integer customernumber;

  public Orders() {
  }

  public Orders(Integer ordernumber, Date orderdate, Date requireddate, Date shippeddate, String status, String comments, Integer customernumber) {
    this.ordernumber = ordernumber;
    this.orderdate = orderdate;
    this.requireddate = requireddate;
    this.shippeddate = shippeddate;
    this.status = status;
    this.comments = comments;
    this.customernumber = customernumber;
  }

  @Id
  @Column(name = "ORDERNUMBER", unique = true)
  public Integer getOrdernumber()
  {
    return this.ordernumber;
  }

  public void setOrdernumber(Integer ordernumber)
  {
    this.ordernumber = ordernumber;
  }

  @Column(name = "ORDERDATE")
  public Date getOrderdate()
  {
    return this.orderdate;
  }

  public void setOrderdate(Date orderdate)
  {
    this.orderdate = orderdate;
  }

  @Column(name = "REQUIREDDATE")
  public Date getRequireddate()
  {
    return this.requireddate;
  }

  public void setRequireddate(Date requireddate)
  {
    this.requireddate = requireddate;
  }

  @Column(name = "SHIPPEDDATE")
  public Date getShippeddate()
  {
    return this.shippeddate;
  }

  public void setShippeddate(Date shippeddate)
  {
    this.shippeddate = shippeddate;
  }

  @Column(name = "STATUS", length = 15)
  public String getStatus()
  {
    return this.status;
  }

  public void setStatus(String status)
  {
    this.status = status;
  }

  @Column(name = "COMMENTS", length = 32700)
  public String getComments()
  {
    return this.comments;
  }

  public void setComments(String comments)
  {
    this.comments = comments;
  }

  @Column(name = "CUSTOMERNUMBER")
  public Integer getCustomernumber()
  {
    return this.customernumber;
  }

  public void setCustomernumber(Integer customernumber)
  {
    this.customernumber = customernumber;
  }

  public boolean equals(Object other)
  {
    if ((this == other)) return true;
    if ((other == null)) return false;
    if (!(other instanceof Orders)) return false;
    Orders castOther = (Orders) other;

    return ((this.getOrdernumber() == castOther.getOrdernumber()) || (this.getOrdernumber() != null && castOther.getOrdernumber() != null && this.getOrdernumber().equals(castOther.getOrdernumber()))) && ((this.getOrderdate() == castOther.getOrderdate()) || (this.getOrderdate() != null && castOther.getOrderdate() != null && this.getOrderdate().equals(castOther.getOrderdate()))) && ((this.getRequireddate() == castOther.getRequireddate()) || (this.getRequireddate() != null && castOther.getRequireddate() != null && this.getRequireddate().equals(castOther.getRequireddate()))) && ((this.getShippeddate() == castOther.getShippeddate()) || (this.getShippeddate() != null && castOther.getShippeddate() != null && this.getShippeddate().equals(castOther.getShippeddate()))) && ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null && castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus()))) && ((this.getComments() == castOther.getComments()) || (this.getComments() != null && castOther.getComments() != null && this.getComments().equals(castOther.getComments()))) && ((this.getCustomernumber() == castOther.getCustomernumber()) || (this.getCustomernumber() != null && castOther.getCustomernumber() != null && this.getCustomernumber().equals(castOther.getCustomernumber())));
  }

  public int hashCode()
  {
    int result = 17;

    result = 37 * result + (getOrdernumber() == null ? 0 : this.getOrdernumber().hashCode());
    result = 37 * result + (getOrderdate() == null ? 0 : this.getOrderdate().hashCode());
    result = 37 * result + (getRequireddate() == null ? 0 : this.getRequireddate().hashCode());
    result = 37 * result + (getShippeddate() == null ? 0 : this.getShippeddate().hashCode());
    result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
    result = 37 * result + (getComments() == null ? 0 : this.getComments().hashCode());
    result = 37 * result + (getCustomernumber() == null ? 0 : this.getCustomernumber().hashCode());
    return result;
  }
}
